import { Specialty, City, Clinic, Doctor, Appointment, Review, ActivityLog, SiteSettings, UserProfile } from '../types';

export const HERO_IMAGE = '/src/assets/images/medicare_hero_clinic_1791042978740.jpg';
export const DOCTOR_MALE_CARDIO = '/src/assets/images/doctor_male_cardio_1791042995523.jpg';
export const DOCTOR_FEMALE_NEURO = '/src/assets/images/doctor_female_neuro_1791043011122.jpg';
export const DOCTOR_FEMALE_PEDIATRICIAN = '/src/assets/images/doctor_female_pediatrician_1791043027782.jpg';
export const DOCTOR_MALE_ORTHOPEDIC = '/src/assets/images/doctor_male_orthopedic_1791043040582.jpg';

export const INITIAL_SPECIALTIES: Specialty[] = [
  {
    id: 'spec-1',
    name: 'Cardiologist',
    slug: 'cardiologist',
    iconName: 'HeartPulse',
    description: 'Heart specialist, blood pressure, chest pain, angiography & cardiovascular disease care.',
    doctorCount: 42,
  },
  {
    id: 'spec-2',
    name: 'Dermatologist',
    slug: 'dermatologist',
    iconName: 'Sparkles',
    description: 'Skin specialist, acne treatment, laser therapy, hair fall & eczema management.',
    doctorCount: 38,
  },
  {
    id: 'spec-3',
    name: 'Gynecologist',
    slug: 'gynecologist',
    iconName: 'HeartHandshake',
    description: 'Women’s health, pregnancy care, high-risk obstetrics & reproductive medicine.',
    doctorCount: 56,
  },
  {
    id: 'spec-4',
    name: 'Neurologist',
    slug: 'neurologist',
    iconName: 'Brain',
    description: 'Brain & nerve specialist, migraine, epilepsy, stroke rehab & spine disorders.',
    doctorCount: 29,
  },
  {
    id: 'spec-5',
    name: 'Pediatrician',
    slug: 'pediatrician',
    iconName: 'Baby',
    description: 'Child specialist, newborn care, vaccinations & pediatric nutrition.',
    doctorCount: 48,
  },
  {
    id: 'spec-6',
    name: 'Orthopedic Surgeon',
    slug: 'orthopedic-surgeon',
    iconName: 'Bone',
    description: 'Bone & joint specialist, fracture management, arthritis & knee replacement.',
    doctorCount: 34,
  },
  {
    id: 'spec-7',
    name: 'Gastroenterologist',
    slug: 'gastroenterologist',
    iconName: 'Stethoscope',
    description: 'Stomach & liver specialist, hepatitis treatment, endoscopy & acidity management.',
    doctorCount: 26,
  },
  {
    id: 'spec-8',
    name: 'General Physician',
    slug: 'general-physician',
    iconName: 'Activity',
    description: 'Internal medicine, fever, diabetes control, thyroid & general health consultation.',
    doctorCount: 65,
  },
];

export const INITIAL_CITIES: City[] = [
  { id: 'city-1', name: 'Lahore', state: 'Punjab', country: 'Pakistan' },
  { id: 'city-2', name: 'Karachi', state: 'Sindh', country: 'Pakistan' },
  { id: 'city-3', name: 'Islamabad', state: 'ICT', country: 'Pakistan' },
  { id: 'city-4', name: 'Rawalpindi', state: 'Punjab', country: 'Pakistan' },
  { id: 'city-5', name: 'Faisalabad', state: 'Punjab', country: 'Pakistan' },
  { id: 'city-6', name: 'Peshawar', state: 'KPK', country: 'Pakistan' },
];

export const INITIAL_CLINICS: Clinic[] = [
  {
    id: 'clinic-1',
    name: 'Doctors Hospital & Medical Center',
    address: '152-G/1, Canal Bank Road, Johar Town',
    cityId: 'city-1',
    cityName: 'Lahore',
    phone: '+92 (042) 111-22-33-77',
    email: 'info@doctorshospital.pk',
    openingHours: '24/7 Emergency · OPD: 09:00 AM - 09:00 PM',
  },
  {
    id: 'clinic-2',
    name: 'Aga Khan University Hospital Executive Clinic',
    address: 'Stadium Road, Bahadurabad',
    cityId: 'city-2',
    cityName: 'Karachi',
    phone: '+92 (021) 111-911-911',
    email: 'appointments@akuh.edu',
    openingHours: 'Mon - Sat: 08:30 AM - 08:00 PM',
  },
  {
    id: 'clinic-3',
    name: 'Shifa International Hospital',
    address: 'Pitras Bukhari Road, Sector H-8/4',
    cityId: 'city-3',
    cityName: 'Islamabad',
    phone: '+92 (051) 846-3000',
    email: 'info@shifa.com.pk',
    openingHours: 'Mon - Sat: 08:00 AM - 09:00 PM',
  },
  {
    id: 'clinic-4',
    name: 'National Hospital & Medical Center DHA',
    address: '132/3-L, Phase 1, DHA',
    cityId: 'city-1',
    cityName: 'Lahore',
    phone: '+92 (042) 111-171-819',
    email: 'info@nationalhospital.com.pk',
    openingHours: 'Mon - Sat: 09:00 AM - 08:30 PM',
  },
  {
    id: 'clinic-5',
    name: 'South City Hospital',
    address: 'Street 1, Block 3, Clifton',
    cityId: 'city-2',
    cityName: 'Karachi',
    phone: '+92 (021) 3586-2301',
    email: 'helpdesk@southcityhospital.org',
    openingHours: 'Mon - Sat: 09:00 AM - 07:30 PM',
  },
];

const DEFAULT_SCHEDULE = [
  { dayOfWeek: 1, dayName: 'Monday', isEnabled: true, startTime: '04:00 PM', endTime: '08:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 2, dayName: 'Tuesday', isEnabled: true, startTime: '04:00 PM', endTime: '08:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 3, dayName: 'Wednesday', isEnabled: true, startTime: '04:00 PM', endTime: '08:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 4, dayName: 'Thursday', isEnabled: true, startTime: '04:00 PM', endTime: '08:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 5, dayName: 'Friday', isEnabled: true, startTime: '04:00 PM', endTime: '08:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 6, dayName: 'Saturday', isEnabled: true, startTime: '02:00 PM', endTime: '06:00 PM', slotDurationMinutes: 20 },
  { dayOfWeek: 0, dayName: 'Sunday', isEnabled: false, startTime: '09:00 AM', endTime: '01:00 PM', slotDurationMinutes: 20 },
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'user-doc-1',
    fullName: 'Prof. Dr. Tariq Mahmood',
    title: 'Prof. Dr. Tariq Mahmood, MBBS, FCPS, FACC',
    email: 'doctor@medicare.com',
    phone: '+92 300 8421093',
    avatarUrl: DOCTOR_MALE_CARDIO,
    specialtyId: 'spec-1',
    specialtyName: 'Cardiologist',
    cityId: 'city-1',
    cityName: 'Lahore',
    clinicId: 'clinic-1',
    clinicName: 'Doctors Hospital & Medical Center',
    clinicAddress: '152-G/1, Canal Bank Road, Johar Town, Lahore',
    experienceYears: 22,
    consultationFee: 2500,
    rating: 4.96,
    reviewCount: 284,
    qualifications: [
      'MBBS - King Edward Medical University (KEMU)',
      'FCPS (Cardiology) - College of Physicians and Surgeons Pakistan',
      'Fellowship in Interventional Cardiology (USA)',
      'Member of Pakistan Cardiac Society (PCS)',
    ],
    bio: 'Prof. Dr. Tariq Mahmood is one of the most senior cardiologists in Lahore with over 22 years of clinical experience. He specializes in coronary angiography, hypertension management, heart failure therapy, and non-invasive cardiovascular diagnostics.',
    languages: ['Urdu', 'English', 'Punjabi'],
    gender: 'male',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-48291-P',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Today',
  },
  {
    id: 'doc-2',
    userId: 'user-doc-2',
    fullName: 'Assoc. Prof. Dr. Ayesha Siddiqa',
    title: 'Dr. Ayesha Siddiqa, MBBS, FCPS (Neurology)',
    email: 'ayesha.siddiqa@medicare.com',
    phone: '+92 321 9401284',
    avatarUrl: DOCTOR_FEMALE_NEURO,
    specialtyId: 'spec-4',
    specialtyName: 'Neurologist',
    cityId: 'city-3',
    cityName: 'Islamabad',
    clinicId: 'clinic-3',
    clinicName: 'Shifa International Hospital',
    clinicAddress: 'Pitras Bukhari Road, Sector H-8/4, Islamabad',
    experienceYears: 15,
    consultationFee: 2200,
    rating: 4.92,
    reviewCount: 168,
    qualifications: [
      'MBBS - Army Medical College (Rawalpindi)',
      'FCPS (Neurology) - CPSP',
      'Clinical Fellowship in Stroke & Epilepsy (UK)',
      'Member of Pakistan Stroke Society',
    ],
    bio: 'Dr. Ayesha Siddiqa is a highly rated consultant neurologist practicing at Shifa International Hospital. She has extensive experience treating migraine, seizures, peripheral neuropathy, Parkinson’s disease, and stroke rehabilitation.',
    languages: ['Urdu', 'English'],
    gender: 'female',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-62940-S',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Today',
  },
  {
    id: 'doc-3',
    userId: 'user-doc-3',
    fullName: 'Dr. Fatima Zahra',
    title: 'Dr. Fatima Zahra, MBBS, MCPS, FCPS (Pediatrics)',
    email: 'fatima.zahra@medicare.com',
    phone: '+92 333 4910248',
    avatarUrl: DOCTOR_FEMALE_PEDIATRICIAN,
    specialtyId: 'spec-5',
    specialtyName: 'Pediatrician',
    cityId: 'city-1',
    cityName: 'Lahore',
    clinicId: 'clinic-4',
    clinicName: 'National Hospital DHA',
    clinicAddress: '132/3-L, Phase 1, DHA, Lahore',
    experienceYears: 13,
    consultationFee: 1800,
    rating: 4.98,
    reviewCount: 310,
    qualifications: [
      'MBBS - Fatima Jinnah Medical University',
      'FCPS (Pediatrics) - CPSP',
      'Certified Pediatric Advanced Life Support (PALS)',
      'Member of Pakistan Pediatric Association (PPA)',
    ],
    bio: 'Dr. Fatima Zahra is an experienced child specialist offering compassionate pediatric consultations, childhood immunization, developmental assessments, newborn wellness checks, and nutritional guidance.',
    languages: ['Urdu', 'English', 'Punjabi'],
    gender: 'female',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-71930-P',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Today',
  },
  {
    id: 'doc-4',
    userId: 'user-doc-4',
    fullName: 'Dr. Usman Khalid',
    title: 'Dr. Usman Khalid, MBBS, FCPS (Orthopedic Surgery), AO Fellow',
    email: 'usman.khalid@medicare.com',
    phone: '+92 301 5521940',
    avatarUrl: DOCTOR_MALE_ORTHOPEDIC,
    specialtyId: 'spec-6',
    specialtyName: 'Orthopedic Surgeon',
    cityId: 'city-2',
    cityName: 'Karachi',
    clinicId: 'clinic-2',
    clinicName: 'Aga Khan University Hospital',
    clinicAddress: 'Stadium Road, Bahadurabad, Karachi',
    experienceYears: 17,
    consultationFee: 2500,
    rating: 4.89,
    reviewCount: 195,
    qualifications: [
      'MBBS - Dow University of Health Sciences (DUHS)',
      'FCPS (Orthopedic Surgery) - CPSP',
      'AO Trauma Fellowship (Switzerland)',
      'Member of Pakistan Orthopaedic Association (POA)',
    ],
    bio: 'Dr. Usman Khalid is a seasoned orthopedic specialist and joint surgeon with expertise in arthroscopic ligament reconstructions, sports injuries, fracture management, and knee osteoarthritis treatments.',
    languages: ['Urdu', 'English', 'Sindhi'],
    gender: 'male',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-51049-K',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Tomorrow',
  },
  {
    id: 'doc-5',
    userId: 'user-doc-5',
    fullName: 'Dr. Mahnoor Khan',
    title: 'Dr. Mahnoor Khan, MBBS, FCPS (Dermatology)',
    email: 'mahnoor.khan@medicare.com',
    phone: '+92 334 1829402',
    avatarUrl: DOCTOR_FEMALE_NEURO,
    specialtyId: 'spec-2',
    specialtyName: 'Dermatologist',
    cityId: 'city-1',
    cityName: 'Lahore',
    clinicId: 'clinic-1',
    clinicName: 'Doctors Hospital & Medical Center',
    clinicAddress: '152-G/1, Canal Bank Road, Johar Town, Lahore',
    experienceYears: 11,
    consultationFee: 2000,
    rating: 4.91,
    reviewCount: 140,
    qualifications: [
      'MBBS - Allama Iqbal Medical College (AIMC)',
      'FCPS (Dermatology) - CPSP',
      'Diploma in Aesthetic Medicine (UK)',
      'Member of Pakistan Association of Dermatologists (PAD)',
    ],
    bio: 'Dr. Mahnoor Khan provides expert clinical and aesthetic dermatological treatments including acne scar management, melasma protocols, eczema care, laser therapies, and hair restoration consultations.',
    languages: ['Urdu', 'English'],
    gender: 'female',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-88492-P',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Today',
  },
  {
    id: 'doc-6',
    userId: 'user-doc-6',
    fullName: 'Dr. Asad Ullah Khan',
    title: 'Dr. Asad Ullah Khan, MBBS, MCPS, FCPS (Medicine)',
    email: 'asad.ullah@medicare.com',
    phone: '+92 300 9184029',
    avatarUrl: DOCTOR_MALE_CARDIO,
    specialtyId: 'spec-8',
    specialtyName: 'General Physician',
    cityId: 'city-2',
    cityName: 'Karachi',
    clinicId: 'clinic-5',
    clinicName: 'South City Hospital',
    clinicAddress: 'Street 1, Block 3, Clifton, Karachi',
    experienceYears: 19,
    consultationFee: 1500,
    rating: 4.94,
    reviewCount: 320,
    qualifications: [
      'MBBS - Sindh Medical College',
      'FCPS (Medicine) - CPSP',
      'Fellow of Royal Society of Medicine',
      'Member of Pakistan Society of Internal Medicine',
    ],
    bio: 'Dr. Asad Ullah Khan is a senior consultant physician providing primary care diagnosis, diabetes mellitus management, hypertension protocols, seasonal viral management, and preventive medical assessments.',
    languages: ['Urdu', 'English', 'Sindhi'],
    gender: 'male',
    isVerified: true,
    isFeatured: true,
    registrationNumber: 'PMDC-39184-K',
    schedules: DEFAULT_SCHEDULE,
    availableToday: true,
    nextAvailableDate: 'Today',
  }
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-patient-1',
    email: 'patient@medicare.com',
    role: 'patient',
    fullName: 'Ahmed Raza Khan',
    phone: '+92 300 1234567',
    dateOfBirth: '1990-05-12',
    gender: 'male',
    bloodGroup: 'B+',
    allergies: ['Penicillin'],
    emergencyContact: 'Zainab Ahmed (+92 300 7654321)',
    address: 'House 42, Block D, Model Town, Lahore',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'user-doc-1',
    email: 'doctor@medicare.com',
    role: 'doctor',
    fullName: 'Prof. Dr. Tariq Mahmood',
    phone: '+92 300 8421093',
    avatarUrl: DOCTOR_MALE_CARDIO,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user-admin-1',
    email: 'admin@medicare.com',
    role: 'admin',
    fullName: 'Admin Operations Desk',
    phone: '+92 (042) 111-CARE (2273)',
    createdAt: '2026-01-01T00:00:00Z',
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    tokenNumber: 'MED-2026-8492',
    patientId: 'user-patient-1',
    patientName: 'Ahmed Raza Khan',
    patientEmail: 'patient@medicare.com',
    patientPhone: '+92 300 1234567',
    patientGender: 'male',
    patientAge: 35,
    doctorId: 'doc-1',
    doctorName: 'Prof. Dr. Tariq Mahmood',
    doctorSpecialty: 'Cardiologist',
    doctorAvatarUrl: DOCTOR_MALE_CARDIO,
    clinicName: 'Doctors Hospital & Medical Center',
    clinicAddress: '152-G/1, Canal Bank Road, Johar Town, Lahore',
    appointmentDate: '2026-10-06',
    appointmentTime: '05:20 PM',
    status: 'confirmed',
    consultationType: 'in-person',
    consultationFee: 2500,
    reasonForVisit: 'Hypertension follow-up and routine cardiac checkup.',
    symptoms: 'Occasional chest heaviness after brisk walking.',
    isFirstVisit: false,
    createdAt: '2026-10-02T14:30:00Z',
    doctorNotes: 'Patient has mild stage-1 hypertension history. Advised resting 12-lead ECG and lipid profile review.',
  },
  {
    id: 'apt-102',
    tokenNumber: 'MED-2026-9104',
    patientId: 'user-patient-1',
    patientName: 'Ahmed Raza Khan',
    patientEmail: 'patient@medicare.com',
    patientPhone: '+92 300 1234567',
    patientGender: 'male',
    patientAge: 35,
    doctorId: 'doc-5',
    doctorName: 'Dr. Mahnoor Khan',
    doctorSpecialty: 'Dermatologist',
    doctorAvatarUrl: DOCTOR_FEMALE_NEURO,
    clinicName: 'Doctors Hospital & Medical Center',
    clinicAddress: '152-G/1, Canal Bank Road, Johar Town, Lahore',
    appointmentDate: '2026-10-10',
    appointmentTime: '06:00 PM',
    status: 'pending',
    consultationType: 'in-person',
    consultationFee: 2000,
    reasonForVisit: 'Skin allergy assessment on arms.',
    symptoms: 'Mild itching after weather change.',
    isFirstVisit: true,
    createdAt: '2026-10-03T07:15:00Z',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    doctorId: 'doc-1',
    patientId: 'user-patient-1',
    patientName: 'Ahmed Raza',
    rating: 5,
    comment: 'Prof. Dr. Tariq Mahmood is an exceptional cardiologist. He listened patiently to my complaints and explained the medication dosage clearly. Very satisfied.',
    visitReason: 'Cardiology Consultation',
    createdAt: '2026-08-25T14:10:00Z',
    isApproved: true,
  },
  {
    id: 'rev-2',
    doctorId: 'doc-3',
    patientId: 'user-patient-3',
    patientName: 'Bilal Hassan',
    rating: 5,
    comment: 'Dr. Fatima Zahra is the best pediatrician in Lahore. She examined my 2-year-old child thoroughly and gave practical advice for infant feeding and immunity.',
    visitReason: 'Child Routine Checkup',
    createdAt: '2026-09-12T11:00:00Z',
    isApproved: true,
  },
  {
    id: 'rev-3',
    doctorId: 'doc-4',
    patientId: 'user-patient-4',
    patientName: 'Mrs. Farooq',
    rating: 5,
    comment: 'Dr. Usman Khalid treated my knee joint pain without unnecessary surgery. Highly recommended for orthopedic problems in Karachi.',
    visitReason: 'Orthopedic Joint Care',
    createdAt: '2026-09-18T16:20:00Z',
    isApproved: true,
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    userName: 'Ahmed Raza Khan',
    userRole: 'patient',
    action: 'BOOK_APPOINTMENT',
    details: 'Booked appointment MED-2026-9104 with Dr. Mahnoor Khan',
    timestamp: '2026-10-03T07:15:00Z',
    ipAddress: '182.185.12.9',
  },
  {
    id: 'log-2',
    userName: 'Prof. Dr. Tariq Mahmood',
    userRole: 'doctor',
    action: 'CONFIRM_APPOINTMENT',
    details: 'Confirmed appointment MED-2026-8492 for Ahmed Raza Khan',
    timestamp: '2026-10-02T15:00:00Z',
    ipAddress: '182.185.12.18',
  }
];

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  siteName: 'MediCare Pakistan',
  siteEmail: 'support@medicare.pk',
  sitePhone: '+92 (042) 111-CARE (2273)',
  emergencyHotline: '1122 / +92 300 1234567',
  address: 'Commercial Plaza, Sector Y, DHA Phase 3, Lahore, Pakistan',
  currencySymbol: 'Rs.',
  appointmentLeadHours: 1,
  slotIntervalMinutes: 20,
  allowPatientCancellation: true,
  maintenanceMode: false,
};
